# Enable mouse
set -g mouse off

# Hide tmux status bar
set -g status off

# Preserve alternate screen behavior
set -ga terminal-overrides ',*:smcup@:rmcup@'

# Better terminal colors
set -g default-terminal "tmux-256color"
